"""Derive icon ink from recorded international pixels, with crop provenance."""
import hashlib
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
CAPTURES = ROOT / '.runtime/bedrock-reference'
OUT = ROOT / 'resource_pack/textures/pyreact_ore/reference'
CASES = [
    ('reference_social', 'audit-edit', [1784, 18, 1836, 66], 'dark'),
    ('reference_friends', 'audit-friends2', [1440, 164, 1488, 204], 'light49'),
    ('reference_team', 'audit-friends2', [1792, 154, 1840, 198], 'light72'),
    ('reference_audio', 'audit-audio-selected-default', [36, 872, 84, 920], None),
    ('reference_video', 'audit-audio-selected-default', [36, 776, 84, 824], None),
    ('reference_account', 'audit-audio-selected-default', [36, 968, 84, 1016], None),
    ('reference_steve_face', 'audit-friends2', [1328, 348, 1424, 444], None),
    ('reference_search', 'round5-search-default', [1312, 48, 1360, 96], 'light49'),
]


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    records = {}
    for name, stem, box, ink in CASES:
        source = CAPTURES / (stem + '.png')
        image = Image.open(source).convert('RGBA').crop(box)
        if ink:
            # Explicit foreground extraction from a uniform surface, retaining
            # CSS edge coverage. No text, skin or geometry is copied into UI.
            pixels = []
            for r, g, b, unused in image.getdata():
                background = 72 if ink == 'light72' else 49
                coverage = (230 - r) / 200.0 if ink == 'dark' else (r - background) / (255.0 - background)
                pixels.append((255, 255, 255, max(0, min(255, round(coverage * 255)))))
            image.putdata(pixels)
        translation = None
        if name in ('reference_friends', 'reference_team'):
            # The recorded crop has asymmetric empty padding. Keep its canvas
            # and native ink intact, but center that ink for an icon-only tab.
            bounds = image.getchannel('A').getbbox()
            dx = round((image.width - bounds[0] - bounds[2]) / 2)
            centered = Image.new('RGBA', image.size)
            centered.paste(image, (dx, 0))
            image = centered
            translation = [dx, 0]
        target = OUT / (name + '.png')
        image.save(target)
        metadata = json.loads(source.with_suffix('.json').read_text('utf8'))
        records[name] = dict(src='textures/pyreact_ore/reference/' + name,
            size=list(image.size), source_capture=source.name, crop=box,
            reference_scale=4, version=metadata['version'],
            source_sha256=hashlib.sha256(source.read_bytes()).hexdigest(),
            extraction=ink or 'RGBA crop')
        if translation is not None:
            records[name]['canvas_translation'] = translation
    (ROOT / 'assets/reference-icons.json').write_text(json.dumps(records, indent=2) + '\n', 'utf8')
    catalog = {name: dict(src=row['src'], size=row['size']) for name, row in records.items()}
    (ROOT / 'oreui/_reference_assets.py').write_text(
        '# Generated by tools/build_reference_assets.py.\nASSETS = ' + repr(catalog) + '\n', 'utf8')


if __name__ == '__main__':
    build()
