"""Resolve screenshot-verified settings copy from the installed Chinese locale."""
import argparse
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]


def build(source):
    translations={}
    for line in source.read_text('utf-8-sig').splitlines():
        if '=' in line and not line.startswith('#'):
            key,value=line.split('=',1)
            translations[key]=value.split('\t#',1)[0].rstrip()
    descriptions={}
    for key,value in translations.items():
        if key.startswith('options.') and key.endswith('.description'):
            stem=key[:-12]
            label=translations.get(stem+'.name',translations.get(stem))
            if label:
                descriptions[label]=value
    target=ROOT/'examples/demo/behavior_pack/ore_demo/settings_copy.py'
    # ASCII Unicode literals work in the embedded narrow Python 2 interpreter.
    # Python 2 needs the unicode marker for JSON-style escaped strings.
    import json
    target.write_text('# -*- coding: utf-8 -*-\n# Generated by tools/build_settings_copy.py.\nimport json\nDESCRIPTIONS = json.loads(r\'\'\''+
        json.dumps(descriptions,ensure_ascii=True,separators=(',',':'))+"''')\n",'utf8')


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--source',type=Path,default=Path('D:/Program/Minecraft/data/resource_packs/vanilla/texts/zh_CN.lang'))
    build(p.parse_args().source)
